/**
 * These tests are from esprima-parser
 * ===================================
 * github: https://github.com/ariya/esprima
 * homepage: http://www.esprima.org
 *
 * Original License
 * ----------------
 * Copyright (C) 2012, 2011 Ariya Hidayat (twitter: @ariyahidayat) and other contributors.
 * Redistribution and use in source and binary forms, with or without modification, are 
 * permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this list of 
 *   conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, this list 
 *   of conditions and the following disclaimer in the documentation and/or other 
 *   materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS 
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED 
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
module.exports = {
  "42":"42",
  "(function(){ var x = 1, y = 2, z = 3 })":"(function(){var x=1,y=2,z=3})",
  "var x = 1, y = 2, z = 3":"var x=1,y=2,z=3",
  "(function(){ { var x = 1, y = 2, z = 3 } })":"(function(){{var x=1,y=2,z=3}})",
  "(function(){ var x, y, z })":"(function(){var x,y,z})",
  "var x, y, z":"var x,y,z",
  "(function(){ { var x, y, z } })":"(function(){{var x,y,z}})",
  "(function(){ function foo() { } })":"(function(){function foo(){}})",
  "function foo() { }":"function foo(){}",
  "(function(){ { function foo() { } } })":"(function(){{function foo(){}}})",
  "(function(){ function foo() { return 42 } })":"(function(){function foo(){return 42}})",
  "function foo() { return 42 }":"function foo(){return 42}",
  "(function(){ { function foo() { return 42 } } })":"(function(){{function foo(){return 42}}})",
  "(function(){ function f(a) { function a() { } } })":"(function(){function f(a){function a(){}}})",
  "function f(a) { function a() { } }":"function f(a){function a(){}}",
  "(function(){ { function f(a) { function a() { } } } })":"(function(){{function f(a){function a(){}}}})",
  "(function(){ function f(a,b,c) { function b() { } } })":"(function(){function f(a,b,c){function b(){}}})",
  "function f(a,b,c) { function b() { } }":"function f(a,b,c){function b(){}}",
  "(function(){ { function f(a,b,c) { function b() { } } } })":"(function(){{function f(a,b,c){function b(){}}}})",
  "(function(){ true })":"(function(){true})",
  "true":"true",

  "(function(){ { true } })":"(function(){{true}})",
  "(function(){ false })":"(function(){false})",
  "false":"false",
  "(function(){ { false } })":"(function(){{false}})",
  "(function(){ 42 })":"(function(){42})",
  "(function(){ { 42 } })":"(function(){{42}})",
  "(function(){ (/asdf/) })":"(function(){(/asdf/)})",
  "(/asdf/)":"(/asdf/)",
  "(function(){ { (/asdf/) } })":"(function(){{(/asdf/)}})",
  "(function(){ this })":"(function(){this})",
  "this":"this",
  "(function(){ { this } })":"(function(){{this}})",
  "(function(){ foo })":"(function(){foo})",
  "foo":"foo",
  "(function(){ { foo } })":"(function(){{foo}})",
  "(function(){ foo.bar })":"(function(){foo.bar})",
  "foo.bar":"foo.bar",
  "(function(){ { foo.bar } })":"(function(){{foo.bar}})",
  "(function(){ foo[bar] })":"(function(){foo[bar]})",
  "foo[bar]":"foo[bar]",
  "(function(){ { foo[bar] } })":"(function(){{foo[bar]}})",
  "(function(){ (function(){}) })":"(function(){(function(){})})",
  "(function(){})":"(function(){})",
  "(function(){ { (function(){}) } })":"(function(){{(function(){})}})",

  "(function(){ (function f() {}) })":"(function(){(function f(){})})",
  "(function f() {})":"(function f(){})",
  "(function(){ { (function f() {}) } })":"(function(){{(function f(){})}})",
  "(function(){ (function f(x,y,z) {}) })":"(function(){(function f(x,y,z){})})",
  "(function f(x,y,z) {})":"(function f(x,y,z){})",
  "(function(){ { (function f(x,y,z) {}) } })":"(function(){{(function f(x,y,z){})}})",
  "(function(){ (++x) })":"(function(){(++x)})",
  "(++x)":"(++x)",
  "(function(){ { (++x) } })":"(function(){{(++x)}})",
  "(function(){ (x++) })":"(function(){(x++)})",
  "(x++)":"(x++)",
  "(function(){ { (x++) } })":"(function(){{(x++)}})",
  "(function(){ (+x) })":"(function(){(+ x)})",
  "(+x)":"(+ x)",
  "(function(){ { (+x) } })":"(function(){{(+ x)}})",
  "(function(){ (-x) })":"(function(){(- x)})",
  "(-x)":"(- x)",
  "(function(){ { (-x) } })":"(function(){{(- x)}})",
  "(function(){ (!x) })":"(function(){(! x)})",
  "(!x)":"(! x)",
  "(function(){ { (!x) } })":"(function(){{(! x)}})",
  "(function(){ (~x) })":"(function(){(~ x)})",
  "(~x)":"(~ x)",

  "(function(){ { (~x) } })":"(function(){{(~ x)}})",
  "(function(){ (delete x) })":"(function(){(delete x)})",
  "(delete x)":"(delete x)",
  "(function(){ { (delete x) } })":"(function(){{(delete x)}})",
  "(function(){ (typeof x) })":"(function(){(typeof x)})",
  "(typeof x)":"(typeof x)",
  "(function(){ { (typeof x) } })":"(function(){{(typeof x)}})",
  "(function(){ (void x) })":"(function(){(void x)})",
  "(void x)":"(void x)",
  "(function(){ { (void x) } })":"(function(){{(void x)}})",
  "(function(){ (x == y) })":"(function(){(x == y)})",

  "(x == y)":"(x == y)",
  "(function(){ { (x == y) } })":"(function(){{(x == y)}})",
  "(function(){ (x != y) })":"(function(){(x != y)})",
  "(x != y)":"(x != y)",
  "(function(){ { (x != y) } })":"(function(){{(x != y)}})",
  "(function(){ (x === y) })":"(function(){(x === y)})",
  "(x === y)":"(x === y)",
  "(function(){ { (x === y) } })":"(function(){{(x === y)}})",


  "(function(){ (x !== y) })":"(function(){(x !== y)})",
  "(x !== y)":"(x !== y)",
  "(function(){ { (x !== y) } })":"(function(){{(x !== y)}})",
  "(function(){ (x < y) })":"(function(){(x < y)})",
  "(x < y)":"(x < y)",
  "(function(){ { (x < y) } })":"(function(){{(x < y)}})",
  "(function(){ (x <= y) })":"(function(){(x <= y)})",
  "(x <= y)":"(x <= y)",
  "(function(){ { (x <= y) } })":"(function(){{(x <= y)}})",
  "(function(){ (x > y) })":"(function(){(x > y)})",
  "(x > y)":"(x > y)",
  "(function(){ { (x > y) } })":"(function(){{(x > y)}})",
  "(function(){ (x >= y) })":"(function(){(x >= y)})",
  "(x >= y)":"(x >= y)",
  "(function(){ { (x >= y) } })":"(function(){{(x >= y)}})",
  "(function(){ (x << y) })":"(function(){(x << y)})",
  "(x << y)":"(x << y)",
  "(function(){ { (x << y) } })":"(function(){{(x << y)}})",
  "(function(){ (x >> y) })":"(function(){(x >> y)})",
  "(x >> y)":"(x >> y)",
  "(function(){ { (x >> y) } })":"(function(){{(x >> y)}})",
  "(function(){ (x >>> y) })":"(function(){(x >>> y)})",
  "(x >>> y)":"(x >>> y)",
  "(function(){ { (x >>> y) } })":"(function(){{(x >>> y)}})",
  "(function(){ (x + y) })":"(function(){(x + y)})",
  "(x + y)":"(x + y)",
  "(function(){ { (x + y) } })":"(function(){{(x + y)}})",
  "(function(){ (w + x + y + z) })":"(function(){(w + x + y + z)})",
  "(w + x + y + z)":"(w + x + y + z)",
  "(function(){ { (w + x + y + z) } })":"(function(){{(w + x + y + z)}})",
  "(function(){ (x - y) })":"(function(){(x - y)})",
  "(x - y)":"(x - y)",
  "(function(){ { (x - y) } })":"(function(){{(x - y)}})",
  "(function(){ (w - x - y - z) })":"(function(){(w - x - y - z)})",


  "(w - x - y - z)":"(w - x - y - z)",
  "(function(){ { (w - x - y - z) } })":"(function(){{(w - x - y - z)}})",
  "(function(){ (x * y) })":"(function(){(x * y)})",
  "(x * y)":"(x * y)",
  "(function(){ { (x * y) } })":"(function(){{(x * y)}})",
  "(function(){ (x / y) })":"(function(){(x / y)})",
  "(x / y)":"(x / y)",
  "(function(){ { (x / y) } })":"(function(){{(x / y)}})",
  "(function(){ (x % y) })":"(function(){(x % y)})",
  "(x % y)":"(x % y)",
  "(function(){ { (x % y) } })":"(function(){{(x % y)}})",
  "(function(){ (x | y) })":"(function(){(x | y)})",
  "(x | y)":"(x | y)",
  "(function(){ { (x | y) } })":"(function(){{(x | y)}})",
  "(function(){ (x ^ y) })":"(function(){(x ^ y)})",
  "(x ^ y)":"(x ^ y)",
  "(function(){ { (x ^ y) } })":"(function(){{(x ^ y)}})",
  "(function(){ (x & y) })":"(function(){(x & y)})",
  "(x & y)":"(x & y)",
  "(function(){ { (x & y) } })":"(function(){{(x & y)}})",
  "(function(){ (x in y) })":"(function(){(x in y)})",
  "(x in y)":"(x in y)",
  "(function(){ { (x in y) } })":"(function(){{(x in y)}})",
  "(function(){ (x instanceof y) })":"(function(){(x instanceof y)})",
  "(x instanceof y)":"(x instanceof y)",
  "(function(){ { (x instanceof y) } })":"(function(){{(x instanceof y)}})",
  "(function(){ (x = y) })":"(function(){(x=y)})",
  "(x = y)":"(x=y)",
  "(function(){ { (x = y) } })":"(function(){{(x=y)}})",
  "(function(){ (x += y) })":"(function(){(x+=y)})",
  "(x += y)":"(x+=y)",
  "(function(){ { (x += y) } })":"(function(){{(x+=y)}})",
  "(function(){ (x -= y) })":"(function(){(x-=y)})",
  "(x -= y)":"(x-=y)",
  "(function(){ { (x -= y) } })":"(function(){{(x-=y)}})",
  "(function(){ (x *= y) })":"(function(){(x*=y)})",
  "(x *= y)":"(x*=y)",
  "(function(){ { (x *= y) } })":"(function(){{(x*=y)}})",
  "(function(){ (x /= y) })":"(function(){(x/=y)})",
  "(x /= y)":"(x/=y)",
  "(function(){ { (x /= y) } })":"(function(){{(x/=y)}})",
  "(function(){ (x %= y) })":"(function(){(x%=y)})",


  "(x %= y)":"(x%=y)",
  "(function(){ { (x %= y) } })":"(function(){{(x%=y)}})",
  "(function(){ (x <<= y) })":"(function(){(x<<=y)})",
  "(x <<= y)":"(x<<=y)",
  "(function(){ { (x <<= y) } })":"(function(){{(x<<=y)}})",
  "(function(){ (x >>= y) })":"(function(){(x>>=y)})",
  "(x >>= y)":"(x>>=y)",
  "(function(){ { (x >>= y) } })":"(function(){{(x>>=y)}})",
  "(function(){ (x >>>= y) })":"(function(){(x>>>=y)})",
  "(x >>>= y)":"(x>>>=y)",
  "(function(){ { (x >>>= y) } })":"(function(){{(x>>>=y)}})",
  "(function(){ (x |= y) })":"(function(){(x|=y)})",
  "(x |= y)":"(x|=y)",
  "(function(){ { (x |= y) } })":"(function(){{(x|=y)}})",
  "(function(){ (x ^= y) })":"(function(){(x^=y)})",
  "(x ^= y)":"(x^=y)",
  "(function(){ { (x ^= y) } })":"(function(){{(x^=y)}})",
  "(function(){ (x &= y) })":"(function(){(x&=y)})",
  "(x &= y)":"(x&=y)",
  "(function(){ { (x &= y) } })":"(function(){{(x&=y)}})",
  "(function(){ (x || y) })":"(function(){(x || y)})",
  "(x || y)":"(x || y)",
  "(function(){ { (x || y) } })":"(function(){{(x || y)}})",
  "(function(){ (x && y) })":"(function(){(x && y)})",
  "(x && y)":"(x && y)",
  "(function(){ { (x && y) } })":"(function(){{(x && y)}})",
  "(function(){ (w || x || y || z) })":"(function(){(w || x || y || z)})",
  "(w || x || y || z)":"(w || x || y || z)",
  "(function(){ { (w || x || y || z) } })":"(function(){{(w || x || y || z)}})",
  "(function(){ (x ? y : z) })":"(function(){(x?y:z)})",
  "(x ? y : z)":"(x?y:z)",
  "(function(){ { (x ? y : z) } })":"(function(){{(x?y:z)}})",

  "(function(){ (x,y) })":"(function(){(x,y)})",
  "(x,y)":"(x,y)",
  "(function(){ { (x,y) } })":"(function(){{(x,y)}})",
  "(function(){ (x,y,z) })":"(function(){(x,y,z)})",
  "(x,y,z)":"(x,y,z)",
  "(function(){ { (x,y,z) } })":"(function(){{(x,y,z)}})",
  "(function(){ (a,b,c,d,e,f,g) })":"(function(){(a,b,c,d,e,f,g)})",
  "(a,b,c,d,e,f,g)":"(a,b,c,d,e,f,g)",
  "(function(){ { (a,b,c,d,e,f,g) } })":"(function(){{(a,b,c,d,e,f,g)}})",
  "(function(){ (new Object) })":"(function(){(new Object)})",
  "(new Object)":"(new Object)",
  "(function(){ { (new Object) } })":"(function(){{(new Object)}})",
  "(function(){ (new Object()) })":"(function(){(new Object())})",
  "(new Object())":"(new Object())",
  "(function(){ { (new Object()) } })":"(function(){{(new Object())}})",
  "(function(){ (new Object(42)) })":"(function(){(new Object(42))})",
  "(new Object(42))":"(new Object(42))",
  "(function(){ { (new Object(42)) } })":"(function(){{(new Object(42))}})",
  "(function(){ (new Object(1,2,3)) })":"(function(){(new Object(1,2,3))})",
  "(new Object(1,2,3))":"(new Object(1,2,3))",
  "(function(){ { (new Object(1,2,3)) } })":"(function(){{(new Object(1,2,3))}})",
  "(function(){ (String()) })":"(function(){(String())})",
  "(String())":"(String())",
  "(function(){ { (String()) } })":"(function(){{(String())}})",
  "(function(){ (String(42)) })":"(function(){(String(42))})",
  "(String(42))":"(String(42))",
  "(function(){ { (String(42)) } })":"(function(){{(String(42))}})",
  "(function(){ (String(1,2,3)) })":"(function(){(String(1,2,3))})",
  "(String(1,2,3))":"(String(1,2,3))",
  "(function(){ { (String(1,2,3)) } })":"(function(){{(String(1,2,3))}})",
  "(function(){ [] })":"(function(){[]})",
  "[]":"[]",
  "(function(){ { [] } })":"(function(){{[]}})",
  "(function(){ [1] })":"(function(){[1]})",
  "[1]":"[1]",
  "(function(){ { [1] } })":"(function(){{[1]}})",
  "(function(){ [1,2] })":"(function(){[1,2]})",
  "[1,2]":"[1,2]",
  "(function(){ { [1,2] } })":"(function(){{[1,2]}})",
  "(function(){ [1,2,3] })":"(function(){[1,2,3]})",
  "[1,2,3]":"[1,2,3]",
  "(function(){ { [1,2,3] } })":"(function(){{[1,2,3]}})",
  "(function(){ [1,,2,3] })":"(function(){[1,,2,3]})",


  "[1,,2,3]":"[1,,2,3]",
  "(function(){ { [1,,2,3] } })":"(function(){{[1,,2,3]}})",
  "(function(){ [1,,,2,3] })":"(function(){[1,,,2,3]})",
  "[1,,,2,3]":"[1,,,2,3]",
  "(function(){ { [1,,,2,3] } })":"(function(){{[1,,,2,3]}})",
  "(function(){ [1,,,2,,3] })":"(function(){[1,,,2,,3]})",
  "[1,,,2,,3]":"[1,,,2,,3]",
  "(function(){ { [1,,,2,,3] } })":"(function(){{[1,,,2,,3]}})",
  "(function(){ [1,,,2,,,3] })":"(function(){[1,,,2,,,3]})",
  "[1,,,2,,,3]":"[1,,,2,,,3]",
  "(function(){ { [1,,,2,,,3] } })":"(function(){{[1,,,2,,,3]}})",
  "(function(){ [,1,2,3] })":"(function(){[,1,2,3]})",
  "[,1,2,3]":"[,1,2,3]",
  
  "(function(){ { [,1,2,3] } })":"(function(){{[,1,2,3]}})",
  "(function(){ [,,1,2,3] })":"(function(){[,,1,2,3]})",
  "[,,1,2,3]":"[,,1,2,3]",
  "(function(){ { [,,1,2,3] } })":"(function(){{[,,1,2,3]}})",
  "(function(){ [,,,1,2,3] })":"(function(){[,,,1,2,3]})",
  "[,,,1,2,3]":"[,,,1,2,3]",
  "(function(){ { [,,,1,2,3] } })":"(function(){{[,,,1,2,3]}})",
  "(function(){ [,,,1,2,3,] })":"(function(){[,,,1,2,3,]})",
  "[,,,1,2,3,]":"[,,,1,2,3,]",
  "(function(){ { [,,,1,2,3,] } })":"(function(){{[,,,1,2,3,]}})",
  "(function(){ [,,,1,2,3,,] })":"(function(){[,,,1,2,3,,]})",
  "[,,,1,2,3,,]":"[,,,1,2,3,,]",
  "(function(){ { [,,,1,2,3,,] } })":"(function(){{[,,,1,2,3,,]}})",
  "(function(){ [,,,1,2,3,,,] })":"(function(){[,,,1,2,3,,,]})",
  "[,,,1,2,3,,,]":"[,,,1,2,3,,,]",
  "(function(){ { [,,,1,2,3,,,] } })":"(function(){{[,,,1,2,3,,,]}})",
  "(function(){ [,,,,,] })":"(function(){[,,,,,]})",
  "[,,,,,]":"[,,,,,]",
  "(function(){ { [,,,,,] } })":"(function(){{[,,,,,]}})",


  "(function(){ ({}) })":"(function(){({})})",
  "({})":"({})",
  "(function(){ { ({}) } })":"(function(){{({})}})",
  "(function(){ ({x:1}) })":"(function(){({x: 1})})",
  "({x:1})":"({x: 1})",
  "(function(){ { ({x:1}) } })":"(function(){{({x: 1})}})",
  "(function(){ ({x:1, y:2}) })":"(function(){({x: 1,y: 2})})",
  "({x:1, y:2})":"({x: 1,y: 2})",
  "(function(){ { ({x:1, y:2}) } })":"(function(){{({x: 1,y: 2})}})",
  "(function(){ ({x:1, y:2, z:3}) })":"(function(){({x: 1,y: 2,z: 3})})",
  "({x:1, y:2, z:3})":"({x: 1,y: 2,z: 3})",
  "(function(){ { ({x:1, y:2, z:3}) } })":"(function(){{({x: 1,y: 2,z: 3})}})",
  "(function(){ ({x:1, 'y':2, z:3}) })":"(function(){({x: 1,\"y\": 2,z: 3})})",
  "({x:1, 'y':2, z:3})":"({x: 1,\"y\": 2,z: 3})",
  "(function(){ { ({x:1, 'y':2, z:3}) } })":"(function(){{({x: 1,\"y\": 2,z: 3})}})",
  "(function(){ ({'x':1, 'y':2, z:3}) })":"(function(){({\"x\": 1,\"y\": 2,z: 3})})",
  "({'x':1, 'y':2, z:3})":"({\"x\": 1,\"y\": 2,z: 3})",
  "(function(){ { ({'x':1, 'y':2, z:3}) } })":"(function(){{({\"x\": 1,\"y\": 2,z: 3})}})",
  "(function(){ ({'x':1, 'y':2, 3:3}) })":"(function(){({\"x\": 1,\"y\": 2,3: 3})})",
  "({'x':1, 'y':2, 3:3})":"({\"x\": 1,\"y\": 2,3: 3})",
  "(function(){ { ({'x':1, 'y':2, 3:3}) } })":"(function(){{({\"x\": 1,\"y\": 2,3: 3})}})",
  "(function(){ 2 + 3 })":"(function(){2 + 3})",
  "2 + 3":"2 + 3",
  "(function(){ { 2 + 3 } })":"(function(){{2 + 3}})",
  "(function(){ typeof(0?0:a) })":"(function(){typeof (0?0:a)})",
  "typeof(0?0:a)":"typeof (0?0:a)",
  "(function(){ { typeof(0?0:a) } })":"(function(){{typeof (0?0:a)}})",
  //"f; if (1) function f(){}":"f; if (1) function f(){}",  //this is no valid es5
  "(function(){ throw 42 })":"(function(){throw 42})",
  "throw 42":"throw 42",
  "(function(){ { throw 42 } })":"(function(){{throw 42}})",
  "(function(){ for (;;) break })":"(function(){for(;;){break }})",
  "for (;;) break":"for(;;){break }",
  "(function(){ { for (;;) break } })":"(function(){{for(;;){break }}})",
  "(function(){ for (x; y; z) break })":"(function(){for(x;y;z){break }})",
  "for (x; y; z) break":"for(x;y;z){break }",
  "(function(){ { for (x; y; z) break } })":"(function(){{for(x;y;z){break }}})",


  "(function(){ for (var x; y; z) break })":"(function(){for(var x;y;z){break }})",
  "for (var x; y; z) break":"for(var x;y;z){break }",
  "(function(){ { for (var x; y; z) break } })":"(function(){{for(var x;y;z){break }}})",
  "(function(){ for (var x = 42; y; z) break })":"(function(){for(var x=42;y;z){break }})",
  "for (var x = 42; y; z) break":"for(var x=42;y;z){break }",
  "(function(){ { for (var x = 42; y; z) break } })":"(function(){{for(var x=42;y;z){break }}})",
  "(function(){ for (x; ; z) break })":"(function(){for(x;;z){break }})",
  "for (x; ; z) break":"for(x;;z){break }",
  "(function(){ { for (x; ; z) break } })":"(function(){{for(x;;z){break }}})",
  "(function(){ for (var x; ; z) break })":"(function(){for(var x;;z){break }})",
  "for (var x; ; z) break":"for(var x;;z){break }",
  "(function(){ { for (var x; ; z) break } })":"(function(){{for(var x;;z){break }}})",
  "(function(){ for (var x = 42; ; z) break })":"(function(){for(var x=42;;z){break }})",
  "for (var x = 42; ; z) break":"for(var x=42;;z){break }",
  "(function(){ { for (var x = 42; ; z) break } })":"(function(){{for(var x=42;;z){break }}})",
  "(function(){ for (x; y; ) break })":"(function(){for(x;y;){break }})",
  "for (x; y; ) break":"for(x;y;){break }",
  "(function(){ { for (x; y; ) break } })":"(function(){{for(x;y;){break }}})",
  "(function(){ for (var x; y; ) break })":"(function(){for(var x;y;){break }})",
  "for (var x; y; ) break":"for(var x;y;){break }",
  "(function(){ { for (var x; y; ) break } })":"(function(){{for(var x;y;){break }}})",
  "(function(){ for (var x = 42; y; ) break })":"(function(){for(var x=42;y;){break }})",
  "for (var x = 42; y; ) break":"for(var x=42;y;){break }",
  "(function(){ { for (var x = 42; y; ) break } })":"(function(){{for(var x=42;y;){break }}})",
  "(function(){ for (var x in y) break })":"(function(){for(var x in y){break }})",
  "for (var x in y) break":"for(var x in y){break }",
  "(function(){ { for (var x in y) break } })":"(function(){{for(var x in y){break }}})",
  "(function(){ for (x in y) break })":"(function(){for(x in y){break }})",
  "for (x in y) break":"for(x in y){break }",
  "(function(){ { for (x in y) break } })":"(function(){{for(x in y){break }}})",
  "(function(){ { } })":"(function(){{}})",
  "{ }":"{}",
  "(function(){ { { } } })":"(function(){{{}}})",
  "(function(){ { throw 1; throw 2; throw 3; } })":"(function(){{throw 1;\nthrow 2;\nthrow 3}})",
  "{ throw 1; throw 2; throw 3; }":"{throw 1;\nthrow 2;\nthrow 3}",
  "(function(){ { { throw 1; throw 2; throw 3; } } })":"(function(){{{throw 1;\nthrow 2;\nthrow 3}}})",
  "(function(){ ; })":"(function(){})",
  ";":"",
  "(function(){ { ; } })":"(function(){{}})",
  "(function(){ if (foo) throw 42; })":"(function(){if(foo){throw 42}})",
  "if (foo) throw 42;":"if(foo){throw 42}",
  "(function(){ { if (foo) throw 42; } })":"(function(){{if(foo){throw 42}}})",
  "(function(){ if (foo) throw 42; else true; })":"(function(){if(foo){throw 42}else{true}})",
  "if (foo) throw 42; else true;":"if(foo){throw 42}else{true}",
  "(function(){ { if (foo) throw 42; else true; } })":"(function(){{if(foo){throw 42}else{true}}})",
  "(function(){ if (foo) { throw 1; throw 2; throw 3; } })":"(function(){if(foo){throw 1;\nthrow 2;\nthrow 3}})",
  "if (foo) { throw 1; throw 2; throw 3; }":"if(foo){throw 1;\nthrow 2;\nthrow 3}",
  "(function(){ { if (foo) { throw 1; throw 2; throw 3; } } })":"(function(){{if(foo){throw 1;\nthrow 2;\nthrow 3}}})",
  "(function(){ if (foo) { throw 1; throw 2; throw 3; } else true; })":"(function(){if(foo){throw 1;\nthrow 2;\nthrow 3}else{true}})",
  "if (foo) { throw 1; throw 2; throw 3; } else true;":"if(foo){throw 1;\nthrow 2;\nthrow 3}else{true}",
  "(function(){ { if (foo) { throw 1; throw 2; throw 3; } else true; } })":"(function(){{if(foo){throw 1;\nthrow 2;\nthrow 3}else{true}}})",
  "(function(){ foo: for(;;) break foo; })":"(function(){foo: for(;;){break foo}})",

  "foo: for(;;) break foo;":"foo: for(;;){break foo}",
  "(function(){ { foo: for(;;) break foo; } })":"(function(){{foo: for(;;){break foo}}})",
  "(function(){ foo: for(;;) continue foo; })":"(function(){foo: for(;;){continue foo}})",
  "foo: for(;;) continue foo;":"foo: for(;;){continue foo}",
  "(function(){ { foo: for(;;) continue foo; } })":"(function(){{foo: for(;;){continue foo}}})",
  "(function(){ with (obj) { } })":"(function(){with(obj){}})",
  "with (obj) { }":"with(obj){}",
  "(function(){ { with (obj) { } } })":"(function(){{with(obj){}}})",
  "(function(){ with (obj) { obj; } })":"(function(){with(obj){obj}})",
  "with (obj) { obj; }":"with(obj){obj}",
  "(function(){ { with (obj) { obj; } } })":"(function(){{with(obj){obj}}})",
  "(function(){ while (foo) { } })":"(function(){while(foo){}})",
  "while (foo) { }":"while(foo){}",
  "(function(){ { while (foo) { } } })":"(function(){{while(foo){}}})",
  "(function(){ while (foo) { foo; } })":"(function(){while(foo){foo}})",
  "while (foo) { foo; }":"while(foo){foo}",
  "(function(){ { while (foo) { foo; } } })":"(function(){{while(foo){foo}}})",
  "(function(){ do { } while (foo); })":"(function(){do{}while(foo)})",
  "do { } while (foo);":"do{}while(foo)",


  "(function(){ { do { } while (foo); } })":"(function(){{do{}while(foo)}})",
  "(function(){ do { foo; } while (foo) })":"(function(){do{foo}while(foo)})",
  "do { foo; } while (foo)":"do{foo}while(foo)",
  "(function(){ { do { foo; } while (foo) } })":"(function(){{do{foo}while(foo)}})",
  "(function(){ switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; } })":"(function(){switch(foo){case 1: 1;break ;case 2: 2;break ;default: 3}})",
  "switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; }":"switch(foo){case 1: 1;break ;case 2: 2;break ;default: 3}",
  "(function(){ { switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; } } })":"(function(){{switch(foo){case 1: 1;break ;case 2: 2;break ;default: 3}}})",
  "(function(){ switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; case 42: 42; } })":"(function(){switch(foo){case 1: 1;break ;case 2: 2;break ;default: 3;case 42: 42}})",
  "switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; case 42: 42; }":"switch(foo){case 1: 1;break ;case 2: 2;break ;default: 3;case 42: 42}",
  "(function(){ { switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; case 42: 42; } } })":"(function(){{switch(foo){case 1: 1;break ;case 2: 2;break ;default: 3;case 42: 42}}})",
  "(function(){ try { } catch (e) { } })":"(function(){try{}catch(e){}})",
  "try { } catch (e) { }":"try{}catch(e){}",
  "(function(){ { try { } catch (e) { } } })":"(function(){{try{}catch(e){}}})",
  "(function(){ try { } catch (e) { } finally { } })":"(function(){try{}catch(e){}finally{}})",
  "try { } catch (e) { } finally { }":"try{}catch(e){}finally{}",
  "(function(){ { try { } catch (e) { } finally { } } })":"(function(){{try{}catch(e){}finally{}}})",
  "(function(){ try { } finally { } })":"(function(){try{}finally{}})",
  "try { } finally { }":"try{}finally{}",

  "(function(){ { try { } finally { } } })":"(function(){{try{}finally{}}})",
  "(function(){ function f() { function g() { } function g() { } } })":"(function(){function f(){function g(){};\nfunction g(){}}})",

  "function f() { function g() { } function g() { } }":"function f(){function g(){};\nfunction g(){}}",
  "(function(){ { function f() { function g() { } function g() { } } } })":"(function(){{function f(){function g(){};\nfunction g(){}}}})",
  "(function(){ function f() { function g() { } function g() { return 42 } } })":"(function(){function f(){function g(){};\nfunction g(){return 42}}})",
  "function f() { function g() { } function g() { return 42 } }":"function f(){function g(){};\nfunction g(){return 42}}",
  "(function(){ { function f() { function g() { } function g() { return 42 } } } })":"(function(){{function f(){function g(){};\nfunction g(){return 42}}}})",
  "(function(){ function f() { var x = 42; var x = 43; } })":"(function(){function f(){var x=42;\nvar x=43}})",
  "function f() { var x = 42; var x = 43; }":"function f(){var x=42;\nvar x=43}",
  "(function(){ { function f() { var x = 42; var x = 43; } } })":"(function(){{function f(){var x=42;\nvar x=43}}})",
  "(function(){ ({ get x() { return 42 } }) })":"(function(){({get x(){return 42}})})",
  "({ get x() { return 42 } })":"({get x(){return 42}})",
  "(function(){ { ({ get x() { return 42 } }) } })":"(function(){{({get x(){return 42}})}})",
  "(function(){ ({ set x(v) { return 42 } }) })":"(function(){({set x(v){return 42}})})",
  "({ set x(v) { return 42 } })":"({set x(v){return 42}})",
  "(function(){ { ({ set x(v) { return 42 } }) } })":"(function(){{({set x(v){return 42}})}})",
  "":""
}
